const ActionTypes = {
  REQUEST_LIST: "REQUEST_LIST",
  CATEGORY_LIST:"CATEGORY_LIST",
  CATEGORY_ID:"CATEGORY_ID",
  CATEGORY_DATA:"CATEGORY_DATA",
  COVER_IMAGE:"COVER_IMAGE",
  MY_PRODUCT:"MY_PRODUCT",
  SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
  SELLER_LIST:"SELLER_LIST",
  SHOPKEEPER_ID:"SHOPKEEPER_ID",
  ORDER_LIST:"ORDER_LIST",
  ORDER_DETAILS:"ORDER_DETAILS",
}

export default ActionTypes