const ActionTypes = {
  REQUEST_LIST: "REQUEST_LIST",
  CATEGORY_LIST:"CATEGORY_LIST",
  CATEGORY_ID:"CATEGORY_ID",
  CATEGORY_DATA:"CATEGORY_DATA",
  COVER_IMAGE:"COVER_IMAGE",
  MY_PRODUCT:"MY_PRODUCT",
}

export default ActionTypes